#!/usr/bin/env bash
#Use while loop to only display username, user id, and home directory path for the user of the file /etc/passwd
#!/usr/bin/env bash
while read -r passwd
	do
		echo "$passwd" | cut -d: ':' -f1,3,6
done > "/etc/passwd"
