#!/usr/bin/env bash
#Tell a story using the contents of /etc/passwd file to replace names, using while loop. 
while IFS=':' read -r username password uid gid homedir shell info
do 
echo "The user $username is part of the $gid gang,"\
  "lives in $homedir and rides $shell."\
  "$uid's place is protected by the passcode $password,"\
  "more info about the user here: $info"
done < "/etc/passwd"
