#!/usr/bin/env bash
#group visitors by IP and HTTP status code, ordered from greatest to lowest occurrence, in list format using awk.
awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
