#!/usr/bin/env bash
#Display Best School 10 times, but the 9th displays Best School and Hi on a new line
count=0
while [ $count -lt 10 ]
do 
echo "Best School"
if [ $count -eq 9 ]
then echo "Hi"
fi 
echo "Best School"
(( count++ )) 
done
