#!/usr/bin/env bash
#Print 1-20 but 4th also displays bad luck from China, 9th bad luck from Japan, 17th bad luck from Italy
count=1

while [ $count -le 20 ]
do 
echo "count"
case $count in
4) echo "bad luck from China";;
9) echo "bad luck from Japan";;
17) echo "bad luck from Italy";;
esac
(( count ++ ))
done
