#!/usr/bin/env bash
#use if state to get information about school file. If the script doesn't exist, print school file does not exist. If the file does exist, print school file exists. Then, check if the file is empty or not, then print if its empty or not empty. Then check if its a regular file, print school is regular file. If not, write nothing.

if [ -e "school" ]
then
echo "school file exists"
if [ -s "school" ]
then
echo "school file is not empty"
else
echo "school file is empty"
fi
if [ -f "school" ]
then
echo "school is a regular file"
fi
else
echo "school file doesn not exist"
fi
